"""Configuration loading for AutoOutreach.

Everything tunable lives in `.env` (secrets + knobs) and `profile.json`
(the only facts the LLM is ever allowed to use about the sender).
Nothing here talks to a paid service -- Groq, Gemini and Gmail SMTP all
run on free tiers.
"""

from __future__ import annotations

import json
import os
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Dict, List

from dotenv import load_dotenv

ROOT = Path(__file__).resolve().parent

# `override=False` so a real environment variable wins over the .env file.
load_dotenv(ROOT / ".env", override=False)


class ConfigError(RuntimeError):
    """Raised when required configuration is missing or nonsensical."""


def _env(key: str, default: str = "") -> str:
    value = os.getenv(key, default)
    return value.strip() if isinstance(value, str) else value


def _env_int(key: str, default: int) -> int:
    raw = _env(key)
    if not raw:
        return default
    try:
        return int(float(raw))
    except ValueError as exc:
        raise ConfigError(f"{key} must be a number, got {raw!r}") from exc


def _env_float(key: str, default: float) -> float:
    raw = _env(key)
    if not raw:
        return default
    try:
        return float(raw)
    except ValueError as exc:
        raise ConfigError(f"{key} must be a number, got {raw!r}") from exc


def _path(key: str, default: str) -> Path:
    raw = _env(key) or default
    p = Path(raw)
    return p if p.is_absolute() else (ROOT / p)


# ---------------------------------------------------------------------------
# Sender profile -- the LLM's only source of truth about Aditya.
# ---------------------------------------------------------------------------
@dataclass
class Profile:
    name: str
    headline: str
    education: Dict[str, Any]
    recent_role: str
    past_internships: List[str]
    skills: Dict[str, List[str]]
    looking_for: str
    links: Dict[str, str]
    raw: Dict[str, Any] = field(default_factory=dict, repr=False)

    @classmethod
    def load(cls, path: Path) -> "Profile":
        if not path.exists():
            raise ConfigError(f"Profile file not found: {path}")
        data = json.loads(path.read_text(encoding="utf-8"))
        missing = [
            k
            for k in (
                "name",
                "headline",
                "education",
                "recent_role",
                "past_internships",
                "skills",
                "looking_for",
                "links",
            )
            if k not in data
        ]
        if missing:
            raise ConfigError(f"profile.json is missing keys: {', '.join(missing)}")
        return cls(
            name=data["name"],
            headline=data["headline"],
            education=data["education"],
            recent_role=data["recent_role"],
            past_internships=list(data["past_internships"]),
            skills=data["skills"],
            looking_for=data["looking_for"],
            links=dict(data["links"]),
            raw=data,
        )

    def facts_block(self) -> str:
        """A compact, verbatim fact sheet handed to the LLM.

        The prompt tells the model these are the ONLY permitted facts, which
        is what keeps generated emails free of invented projects or skills.
        """
        edu = self.education
        lines = [
            f"Name: {self.name}",
            f"Status: {self.headline}",
            f"Degree: {edu.get('degree', '')} at {edu.get('institute', '')}"
            + (f", CGPA {edu['cgpa']}" if edu.get("cgpa") else ""),
            f"Most recent experience: {self.recent_role}",
            "Earlier internships: " + ", ".join(self.past_internships),
            "Full-stack skills: " + ", ".join(self.skills.get("full_stack", [])),
            "GenAI / LLM skills: " + ", ".join(self.skills.get("genai", [])),
            f"Looking for: {self.looking_for}",
            "IMPORTANT: the skills above are general skills. This fact sheet "
            "does NOT record which skills were used at which employer, so you "
            "must not connect any skill to any company, and must not describe "
            "what was built at any internship.",
        ]
        return "\n".join(f"- {ln}" for ln in lines if ln.strip(" -"))

    def signature(self, sender_name: str | None = None) -> str:
        """Deterministic signature block -- never generated by the LLM,
        so the links can't be mangled or hallucinated."""
        lines = ["--", sender_name or self.name]
        for label, url in self.links.items():
            lines.append(f"{label}: {url}")
        return "\n".join(lines)


# ---------------------------------------------------------------------------
# Runtime settings
# ---------------------------------------------------------------------------
@dataclass
class Settings:
    groq_api_key: str
    groq_model: str
    gemini_api_key: str
    gemini_model: str

    gmail_address: str
    gmail_app_password: str
    sender_name: str
    test_recipient: str
    reply_to: str

    send_delay_min: float
    send_delay_max: float
    daily_send_cap: int

    contacts_csv: Path
    profile_json: Path
    sent_log_csv: Path
    outbox_dir: Path
    log_dir: Path

    max_body_words: int
    llm_max_retries: int
    llm_backoff_base: float

    @classmethod
    def load(cls) -> "Settings":
        gmail = _env("GMAIL_ADDRESS")
        delay_min = _env_float("SEND_DELAY_MIN", 45.0)
        delay_max = _env_float("SEND_DELAY_MAX", 60.0)
        if delay_max < delay_min:
            delay_min, delay_max = delay_max, delay_min
        return cls(
            groq_api_key=_env("GROQ_API_KEY"),
            # Providers retire models; `python main.py --list-models` shows
            # what the configured keys can actually reach today.
            groq_model=_env("GROQ_MODEL") or "openai/gpt-oss-120b",
            gemini_api_key=_env("GEMINI_API_KEY"),
            gemini_model=_env("GEMINI_MODEL") or "gemini-2.5-flash",
            gmail_address=gmail,
            # Gmail shows App Passwords as "abcd efgh ijkl mnop"; spaces are noise.
            gmail_app_password=_env("GMAIL_APP_PASSWORD").replace(" ", ""),
            sender_name=_env("SENDER_NAME"),
            test_recipient=_env("TEST_RECIPIENT") or gmail,
            reply_to=_env("REPLY_TO") or gmail,
            send_delay_min=delay_min,
            send_delay_max=delay_max,
            daily_send_cap=_env_int("DAILY_SEND_CAP", 40),
            contacts_csv=_path("CONTACTS_CSV", "companies.csv"),
            profile_json=_path("PROFILE_JSON", "profile.json"),
            sent_log_csv=_path("SENT_LOG_CSV", "sent_log.csv"),
            outbox_dir=_path("OUTBOX_DIR", "outbox"),
            log_dir=_path("LOG_DIR", "logs"),
            max_body_words=_env_int("MAX_BODY_WORDS", 120),
            llm_max_retries=_env_int("LLM_MAX_RETRIES", 4),
            llm_backoff_base=_env_float("LLM_BACKOFF_BASE", 2.0),
        )

    # -- validation -------------------------------------------------------
    def require_llm(self) -> None:
        if not self.groq_api_key and not self.gemini_api_key:
            raise ConfigError(
                "No LLM key configured. Set GROQ_API_KEY (free: "
                "https://console.groq.com/keys) and/or GEMINI_API_KEY (free: "
                "https://aistudio.google.com/apikey) in .env"
            )

    def require_smtp(self) -> None:
        missing = [
            k
            for k, v in (
                ("GMAIL_ADDRESS", self.gmail_address),
                ("GMAIL_APP_PASSWORD", self.gmail_app_password),
            )
            if not v
        ]
        if missing:
            raise ConfigError(
                "Missing "
                + ", ".join(missing)
                + " in .env. Create a Gmail App Password at "
                "https://myaccount.google.com/apppasswords (free; requires 2FA)."
            )
        if not self.sender_name:
            self.sender_name = self.gmail_address
